include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/xly.dart
    - user_code/**
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
