name: xly
description: "A Test Flutter Package， DO NOT USE IT at present"
version: 0.21.0

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # need reexport
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  window_manager: ^0.5.1
  screen_retriever: ^0.2.0
  lottie: ^3.1.2
  get_storage: ^2.1.1
  ffi: ^2.1.3
  win32: ^5.9.0
  tray_manager: ^0.5.1
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.0

  # no need reexport
  flutter_adaptive_scaffold: ^0.1.7+1
  flutter_inset_shadow: ^2.0.3
  url_launcher: ^6.2.5
  path: ^1.8.0
  xml: ^6.5.0
  icons_launcher: ^3.0.0
  image: ^4.5.3
  args: ^2.6.0


  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  autostart_settings: ^0.1.4
  launch_at_startup: ^0.3.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

example: example

executables:
  rename: rename
  generate: generate
